<?php
$mess=array(
	"imagetype" => "<span style='color:green;'>Sorry, only JPG, JPEG, PNG & GIF files are allowed.</span>",
	"wallet_unavailable" => "<span style='color:green;'>Sorry, this driver's wallet is not available.</span>",
	"driver_unavailable" => "<span style='color:green;'>Sorry, this driver is not available or driver id is wrong.</span>",
	"xlstype" => "<span style='color:green;'>Sorry, only XLSX files are allowed.</span>",
	"select_msg"=>"<span style='color:green;'>Please select city.</span>",
	"add_settle"=>"<span style='color:green;'>Record has been settled successfully.</span>",
	"wallet_upd"=>"<span style='color:green;'>Wallet updated successfully.</span>",
	"wallet_error"=>"<span style='color:green;'>Invalid Amount.</span>",
	"not_auth"=>"<span style='color:green;'>You are not authorized to do this action.</span>",
	"login"=>"<span style='color:green;'>You are logged in successfully.</span>",
	"del"=>"<span style='color:green;'>Record has been deleted successfully.</span>",
	"restore"=>"<span style='color:green;'>Record has been restored successfully.</span>",
	"delete_attr"=>"<span style='color:green;'>Attribute has been deleted successfully.</span>",
	"multidel"=>"<span style='color:green;'>Selected records has been deleted successfully.</span>",
	"multiact"=>"<span style='color:green;'>Selected records has been activated successfully.</span>",
	"actattr"=>"<span style='color:green;'>This attribute has been activated successfully.</span>",
	"inactattr"=>"<span style='color:green;'>This attribute has been inactivated successfully.</span>",
	"multiinact"=>"<span style='color:green;'>Selected records has been deactivated successfully.</span>",
	"highlighted"=>"<span style='color:green;'>Selected records has been Highlight successfully.</span>",
	"nothighlighted"=>"<span style='color:green;'>Selected records has been No Highlight successfully.</span>",
	"add"=>"<span style='color:green;'>Record has been inserted successfully.</span>",
	"success_push"=>"<span style='color:green;'>Push notification successfully send.</span>",
	"success_msg"=>"<span style='color:green;'>Message successfully send.</span>",
	"cityexit"=>"<span style='color:green;'>Record has been already exist.</span>",
	"vihicleexist"=>"<span style='color:green;'>Vihicle has been already exist.</span>",
	"email_exit"=>"<span style='color:green;'>Email has been already exist.</span>",
	"insertcomment"=>"<span style='color:green;'>Comment has been inserted successfully.</span>",
	"edit"=>"<span style='color:green;'>Record has been updated successfully.</span>",
	"key_exit"=>"<span style='color:green;'>Key already exist.</span>",
	"orderupdate"=>"<span style='color:green;'>Ordering updated successfully.</span>",

	"insertcommenterror"=>"<span style='color:red;'>Error Occured! Comment has not been insert!</span>",

	"logout"=>"<span style='color:green;'>You are logged out successfully.</span>",
	"nameexists"=>"Entered Name already exists.",
	"urlexists"=>"Entered Url already exists.",
	"emailexists"=>"Entered Email already exists.",
	"codeexists"=>"Entered Code already exists.",
	"bankexists"=>"Entered Bank name already exists.",
	"keyexists"=>"Key name already exists.",
	"phoneexists"=>"Entered Phone already exists.",
	"couponexists"=>"Entered Coupon already exists.",
	"passwordmismatch"=>"Password fields are not matching.",
	"invalid"=>"<span style='color:red;'>Invalid Usename/Password</span>",
	"invaliduser"=>"<span style='color:red;'>Username does not exists. Please Try Again</span>",
	"editinfo"=>"Your details has been changed successfully.",
	"chgstus"=>"Content has been publised successfully!!",
	"restore"=>"The page was restored successfully.",
	"order"=>"Menu Items Reordered Successfully!!",
	"newssent"=>"Newsletter has been sent successfully!!",
	"error"=>"<span style='color:red;'>Error Occured! Mail has not been sent!</span>",
	"sessionexpire"=>"Your session has been expire! Please login agint to access Admin.",
	"filedel"=>"File has been Removed!",
	"logfirst"=>"<span style='color:red;'>Please, Login first!</span>",
	"nochpass"=>"<span style='color:red;'>You have entered wrong password. Please Try Again</span>",
	"chpass"=>"Your password has been changed successfully!!",
	"setsave"=>"Settings has been changed successfully!",
	"newssend"=>"Newsletter has been sent to subscribe users.",
	"sameuser"=>"<span style='color:red;'>User name already exist!!</span>",
	"reg"=>"You have successfully registerd to our site. Please login to proceed.",
	"loginfirst"=>"<span style='color:red;'>Please, Login First !!</span>",
	"passsent"=>"Your Password has been sent to your email address.",
	"emailnotexist"=>"<span style='color:red;'>E-Mail Address you have entered does not exist. Please Try Again.</span>",
	"emailsent"=>"Thank you! Your enquiry has been sent to administrator",
	"orsentdel"=>"Order has been sent! member info has been deleted from database.",
	"reviewadd"=>"Thank You! Your review has been submitted.",
	"csvuploaded"=>"Order CSV uploaded successfully!!",
	"addimg"=>"Image uploaded successfully!!",
	"delimg"=>"Image deleted successfully!!",
	"active"=>"Record has been activated",
	"activecomment"=>"Comment has been activated",
	"inactivecomment"=>"Comment has been inactivated",
	"deletecomment"=>"Comment has been deleted",
	"imageonly"=>"<span style='color:red;'>Please upload image only</span>",
	"sameemail"=>"<span style='color:red;'>Email address already exists</span>",
	"userinactive"=>"<span style='color:red;'>Your account is inactive. Please contact administrator.</span>",
	"queexist"=>"<span style='color:red;'>Question already exists.</span>",
	"alreadybookmarked"=>"You have already saved this article in your list",
	"bookmarksaved"=>"Article has been saved to your list",
	"inqsent"=>"Your inquiry has been sent to us. We will contact you as soon as possible",
	"artsub"=>"Thank you! Your article has been submitted successfully! Once Admin will approve your article, it will be list into site.",
	"invsent"=>"Invitation sent successfully.",
	"ratesucc"=>"Thanks for your rating!",
	"commentsucc"=>"Thanks For your comments. Once administrator will approve your comment, it will display on site",
	"cmtflgd"=>"Thank you! Your report has been submitted successfully.",
	"frdexist"=>"You have already added this user as a friend.",
	"frdadded"=>"You have successfully added this user as a Friend.",
	"itsyou"=>"You can't add yourself as a Friend.",
	"required"=>"<span style='color:red;'>Please enter all fields.</span>",
	"subscribesuccess"=>"You have successfully subscribed to our newsletter.",
	"alreadysubscribed"=>"You are already registered.",
	"permissiondenied"=>"You have not  access permission.",
	"titleexist"=>"<span style='color:red;'>Title already exists.</span>",
	"del_item"=>"Menu Link deleted successfully.",
	"test_email_sent"=>"Email sent successfully.",
	"test_email_not_sent"=>"Email can't sent.",
	"model_code_exists"=>"Model Code already exists.",
	
	"file_missing" => "File not found. Please upload file.",
	"not_xlsx" => 'File type is not valid. Please upload ".XLSX" file.',
	"col_mismatch" => 'Columns are mismatch. Please upload proper ".XLSX" file.',
	
	"massupload_general" => 'General mass upload done successfully.',
	"massupload_import" => 'Import mass upload done successfully.',
	"massupload_pos" => 'POS mass upload done successfully.',
	"massupload_price" => 'Price mass upload done successfully.',
	"massupload_live" => 'Live products mass upload done successfully.',
	"massupload_pos_id" => 'POS Product ID uploaded successfully.',
	
	
	"payment_status_changed"=>"Payment status updated successfully!!",
	"order_status_changed"=>"Order status updated successfully!!",
	"remark_added"=>"Remark Added successfully!!",
	"remark_sent"=>"Remark sent successfully!!",
	"file_exported"=>"File exported successfully!!",
	"no_data_available"=>"No data found for your selected criteria!!",
	
	"img_delete"=>"Image deleted successfully!!",
	
	"atleast_one_id"=>"Add atleast one Product ID.",
	"id_added"=>"Product ID added successfully!!.",
	"tracking_sent"=>"Tracking email sent successfully!!.",
	"tracking_not_sent"=>"Tracking email can't sent successfully!!.",
	
	"productid_exists"=> "Model Code already Exists.",
	"shortname_exists"=>"Short Name already Exists.",
	"backup_created"=>"Backup created successfully!!.",
	"backup_not_found"=>"Database backup file not found!!.",
	"backup_restored"=>"Database restored successfully!!.",
	
	
);
?>